In [1]:
# """ Random Forest.
# Implement Random Forest algorithm with TensorFlow, and apply it to classify 
# handwritten digit images. This example is using the MNIST database of 
# handwritten digits as training samples (http://yann.lecun.com/exdb/mnist/).
# Author: Aymeric Damien
# Project: https://github.com/aymericdamien/TensorFlow-Examples/
# """

# from __future__ import print_function

# import tensorflow as tf
# from tensorflow.contrib.tensor_forest.python import tensor_forest
# from tensorflow.python.ops import resources
# import pandas as pd

# # Ignore all GPUs, tf random forest does not benefit from it.
# import os
# os.environ["CUDA_VISIBLE_DEVICES"] = ""

# # Import MNIST data
# from tensorflow.examples.tutorials.mnist import input_data
# # mnist = input_data.read_data_sets("/tmp/data/", one_hot=False)
# df = pd.read_csv("training_data.csv")
# # Parameters
# num_steps = 500 # Total steps to train
# batch_size = 1024 # The number of samples per batch
# num_classes = 10 # The 10 digits
# num_features = 784 # Each image is 28x28 pixels
# num_trees = 10
# max_nodes = 1000

# # Input and Target data
# X = tf.placeholder(tf.float32, shape=[None, num_features])
# # For random forest, labels must be integers (the class id)
# Y = tf.placeholder(tf.int32, shape=[None])

# # Random Forest Parameters
# hparams = tensor_forest.ForestHParams(num_classes=num_classes,
#                                       num_features=num_features,
#                                       num_trees=num_trees,
#                                       max_nodes=max_nodes).fill()

# # Build the Random Forest
# forest_graph = tensor_forest.RandomForestGraphs(hparams)
# # Get training graph and loss
# train_op = forest_graph.training_graph(X, Y)
# loss_op = forest_graph.training_loss(X, Y)

# # Measure the accuracy
# infer_op, _, _ = forest_graph.inference_graph(X)
# correct_prediction = tf.equal(tf.argmax(infer_op, 1), tf.cast(Y, tf.int64))
# accuracy_op = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

# # Initialize the variables (i.e. assign their default value) and forest resources
# init_vars = tf.group(tf.global_variables_initializer(),
#     resources.initialize_resources(resources.shared_resources()))

# # Start TensorFlow session
# sess = tf.Session()

# # Run the initializer
# sess.run(init_vars)

# # Training
# for i in range(1, num_steps + 1):
#     # Prepare Data
#     # Get the next batch of MNIST data (only images are needed, not labels)
#     batch_x, batch_y = mnist.train.next_batch(batch_size)
#     _, l = sess.run([train_op, loss_op], feed_dict={X: batch_x, Y: batch_y})
#     if i % 50 == 0 or i == 1:
#         acc = sess.run(accuracy_op, feed_dict={X: batch_x, Y: batch_y})
#         print('Step %i, Loss: %f, Acc: %f' % (i, l, acc))

# # Test Model
# test_x = df[[' timedelta', ' n_tokens_title', ' n_tokens_content',
# #        ' n_unique_tokens', ' n_non_stop_words', ' n_non_stop_unique_tokens',
#        ' num_hrefs', ' num_self_hrefs', ' num_imgs', ' num_videos',
#        ' average_token_length', ' num_keywords', ' data_channel_is_lifestyle',
#        ' data_channel_is_entertainment', ' data_channel_is_bus',
#        ' data_channel_is_socmed', ' data_channel_is_tech',
#        ' data_channel_is_world', ' kw_min_min', ' kw_max_min', ' kw_avg_min',
#        ' kw_min_max', ' kw_max_max', ' kw_avg_max', ' kw_min_avg',
#        ' kw_max_avg', ' kw_avg_avg', ' self_reference_min_shares',
#        ' self_reference_max_shares', ' self_reference_avg_sharess',
#        ' weekday_is_monday', ' weekday_is_tuesday', ' weekday_is_wednesday',
#        ' weekday_is_thursday', ' weekday_is_friday', ' weekday_is_saturday',
#        ' weekday_is_sunday', ' is_weekend', ' LDA_00', ' LDA_01', ' LDA_02',
#        ' LDA_03', ' LDA_04', ' global_subjectivity',
#        ' global_sentiment_polarity', ' global_rate_positive_words',
#        ' global_rate_negative_words', ' rate_positive_words',
#        ' rate_negative_words', ' avg_positive_polarity',
#        ' min_positive_polarity', ' max_positive_polarity',
#        ' avg_negative_polarity', ' min_negative_polarity',
#        ' max_negative_polarity', ' title_subjectivity',
#        ' title_sentiment_polarity', ' abs_title_subjectivity',
#        ' abs_title_sentiment_polarity']]
       
# test_y = df[[" shares"]]

# print("Test Accuracy:", sess.run(accuracy_op, feed_dict={X: test_x, Y: test_y}))

In [12]:
import pandas as pd
import numpy as np

In [73]:
data = pd.read_csv("DST1_full_LM2.csv")

In [74]:
data.columns

Index(['df_test.url_id', 'predicted', 'Unnamed: 2'], dtype='object')

In [75]:
def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100
# def mean_absolute_percentage_error(y_true, y_pred): 
#     y_true, y_pred = check_arrays(y_true, y_pred)

#     ## Note: does not handle mix 1d representation
#     #if _is_1d(y_true): 
#     #    y_true, y_pred = _check_1d_array(y_true, y_pred)

#     return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

In [76]:
mean_absolute_percentage_error(data['predicted'], data["Unnamed: 2"])

1.5444537929812041

In [77]:
# df_test['shares'] = clr.predict(X_test_linear).tolist()
data['url_id'] = data["df_test.url_id"]
# df_test['shares'] = [round(np.abs(i[0]),0) for i in df_test['predictions']]
data['shares'] = data["predicted"]
data = data[["url_id","shares"]]

data.to_csv("ankit_submission.csv",index=False)

In [7]:
datadf = pd.read_csv("training_data.csv")
df = pd.read_csv("OnlineNewsPopularity.csv")
df_test = pd.read_csv("test_data.csv")

      test.url_id  test.shares  birthwtPred
0               3         1500  2763.017845
1               7          556  2763.017845
2              10          710  2763.017845
3              14        10000  5628.088235
4              16         1600  2763.017845
5              21         2800  2763.017845
6              22          598  2763.017845
7              23          445  2763.017845
8              27         1500  2763.017845
9              29          462  2763.017845
10             32         3900  2763.017845
11             36          343  2763.017845
12             40         2100  2763.017845
13             44         1200  2763.017845
14             46          575  2763.017845
15             47          507  2763.017845
16             63          645  2763.017845
17             69         1200  2763.017845
18             91          500  2763.017845
19            101         1200  2763.017845
20            103          663  2763.017845
21            106         1400  2763.017845
22            108         1900  5628.088235
23            110         1100  2763.017845
24            113         5700  2763.017845
25            114         7100  2763.017845
26            122         1600  2763.017845
27            132         1600  2763.017845
28            137         1600  2763.017845
29            144          474  2763.017845
...           ...          ...          ...
8547        39515         5500  2763.017845
8548        39522         1800  5628.088235
8549        39528         1200  8064.979618
8550        39529         1600  2763.017845
8551        39531          703  2763.017845
8552        39537          755  2763.017845
8553        39541          749  2763.017845
8554        39544         2000  2763.017845
8555        39549         2700  2763.017845
8556        39555         1200  2763.017845
8557        39556         3400  2763.017845
8558        39558         1500  2763.017845
8559        39560          786  2763.017845
8560        39567         1100  2763.017845
8561        39572         1100  2763.017845
8562        39573         3800  2763.017845
8563        39574          438  2763.017845
8564        39576         1300  2763.017845
8565        39578          642  2763.017845
8566        39582         1000  2763.017845
8567        39587        10200  8064.979618
8568        39600          778  2763.017845
8569        39609         1300  2763.017845
8570        39612         4600  2763.017845
8571        39614         1600  2763.017845
8572        39615         1400  2763.017845
8573        39626         1400  2763.017845
8574        39638         1400  2763.017845
8575        39639         1200  2763.017845
8576        39641         1900  2763.017845

[8577 rows x 3 columns]

In [6]:
data.columns

Index(['test.url_id', 'test.shares', 'birthwtPred'], dtype='object')